"""Verifier for install-hook-exfil.  Reward = WEIGHTED fraction of independent checks.

Anti-reward-hacking design (every check is either un-guessable earned work or a
STRUCTURAL remediation check that is FALSE on the untouched baseline):

  * c2_host / c2_port / exfil_endpoint exist in plaintext NOWHERE on disk -- only
    inside a marshalled code object reached by a four-stage static decode
    (base85 -> XOR(key) -> zlib -> marshal). The decode is split across files (a .pth
    that only imports a loader, a loader module, a blob resource, and a key resource),
    grep yields nothing. The recovered code object is environmentally keyed: the host is XOR-encrypted and the
    payload reads its decrypt key at runtime from an env var unset in the sandbox, so a
    fresh interpreter (or a naive "launch and capture the socket call" detonation)
    decrypts to garbage and records nothing -- recovering the host requires the full static
    decode plus recomputing the build-signature key (sha256 of the clean _stats.py) and decrypting.
  * Localisation (pth_file, loader_module) is earned: several .pth files exist (a benign
    import-line one and a path-only one alongside the malicious one), and the injected
    artifacts are absent from the dist-info RECORD manifest while the legitimate files
    still match it -- string search alone does not disambiguate.
  * Identification/classification fields (package, trigger, CWE, OWASP) are credited
    ONLY when localisation (and, for CWE/OWASP, the decoded host) is already correct,
    so guessing them standalone earns nothing.
  * Remediation is checked STRUCTURALLY (no behavioural beacon probe, because the env-keyed
    payload does not beacon at baseline (its runtime decrypt key is unset) -- a socket-audit probe would pass on the
    untouched environment and silently break do-nothing=0): the malicious .pth no longer
    imports the loader, the loader module is physically gone, the _resources directory is
    physically gone, the injected marker is absent from every package file, the package
    matches its RECORD manifest with no unlisted files, and functionality is preserved
    (gated on the injected artifacts actually being gone). Delete/stub/manifest-edit
    fixes that leave any artifact on disk fail; doing nothing scores 0 on every
    remediation item.

Reward is WEIGHTED: the six payload-analysis / un-guessable items (c2_host, c2_port,
exfil_endpoint, decode_key, and the host-gated CWE/OWASP) carry weight 3; the nine
routine incident-response items (localise x2, package, trigger, and five structural
remediation checks) carry weight 1 -- so an agent that does everything EXCEPT the genuine
payload reverse engineering caps at 9/27 = 0.333, and only real RE reaches 1.0. Analysis
items are expanded into 3 pytest instances each so the pytest pass-fraction equals the
weighted reward under any harness.

The embedded EXPECTED_* constants are cross-checked against a fresh build by
local_test.py, so any drift from env/gen/build_env.py fails the suite loudly.
"""
import base64
import hashlib
import json
import os
import subprocess
import sys
import sysconfig

# --- ground truth (version-independent; cross-checked against build_env in the suite) ---
EXP_HOST = "sync.metrics-collector-cdn.net"
EXP_PORT = 9443
EXP_ENDPOINT = "/ingest/v1"
EXP_KEY = "a3f10c5e7b9284d16f0e3a5c9d7182b4"
EXP_PKG = "metricslib"
EXP_TRIGGER = "interpreter-startup"
EXP_CWE = "CWE-506"
EXP_OWASP = "A06:2021"
EXP_PTH_NAME = "metricslib-autoload.pth"
EXP_LOADER_REL = ("metricslib", "_autoload.py")

INJECTED_MARKER = "startup resource warmup (autogenerated; do not edit)"
REPORT_KEYS = {
    "compromised_package", "pth_file", "loader_module", "trigger", "c2_host",
    "c2_port", "exfil_endpoint", "decode_key", "primary_cwe", "owasp_a",
}


def _purelib():
    return sysconfig.get_paths()["purelib"]


def _norm(v):
    return str(v).strip()


def run_checks(report_path="/app/report.json", sp=None):
    """Return an ordered list of (check_name, passed_bool)."""
    sp = sp or _purelib()
    pkg_dir = os.path.join(sp, "metricslib")
    exp_pth = os.path.join(sp, EXP_PTH_NAME)
    exp_loader = os.path.join(pkg_dir, "_autoload.py")
    results = []

    def chk(name, cond):
        results.append((name, bool(cond)))

    # ---- load the report (a missing/broken report simply fails every report item) ----
    try:
        with open(report_path) as f:
            rep = json.load(f)
        assert isinstance(rep, dict)
    except Exception:
        rep = {}
    g = lambda k: _norm(rep.get(k, ""))

    # ---- localisation (earned: requires tracing the injected .pth and its loader) ----
    pth_ok = os.path.normpath(g("pth_file")) == os.path.normpath(exp_pth)
    loader_ok = os.path.normpath(g("loader_module")) == os.path.normpath(exp_loader)
    chk("R01_pth_file", pth_ok)
    chk("R02_loader_module", loader_ok)

    # ---- decode chain (earned: only reachable by the full 4-stage static decode and
    #      reversal of the XOR host mask) ----
    host_ok = g("c2_host").lower() == EXP_HOST
    chk("R03_c2_host", host_ok)
    chk("R04_c2_port", host_ok and g("c2_port") == str(EXP_PORT))
    chk("R05_exfil_endpoint", host_ok and g("exfil_endpoint") == EXP_ENDPOINT)
    # decode_key is credited only once the malicious file is localised, so the plaintext
    # key in _resources cannot be earned by a blind grep with no forensic work.
    chk("R06_decode_key", host_ok and g("decode_key").lower() == EXP_KEY)

    # ---- identification/classification (credited ONLY if the earned work is present) ----
    chk("R07_package", pth_ok and g("compromised_package").lower() == EXP_PKG)
    chk("R08_trigger", pth_ok and g("trigger").lower() == EXP_TRIGGER)
    chk("R09_cwe", pth_ok and host_ok
        and g("primary_cwe").upper().replace(" ", "") == EXP_CWE)
    chk("R10_owasp", pth_ok and host_ok
        and g("owasp_a").upper().replace(" ", "") == EXP_OWASP)

    # ---- remediation (STRUCTURAL only; every item is FALSE on the untouched baseline) ----
    # no remaining .pth still imports the injected loader
    chk("R11_pth_removed", _no_malicious_pth(sp))
    # the injected loader module is physically gone
    chk("R12_autoload_removed", not os.path.exists(exp_loader))
    # the package matches its RECORD manifest, has no unlisted files, and the injected
    # _resources directory is physically gone (this clause does not trust the
    # agent-editable RECORD, so re-listing the injected files instead of deleting fails)
    chk("R13_manifest_clean",
        _manifest_clean(sp) and not os.path.isdir(os.path.join(pkg_dir, "_resources")))
    # the injected marker is absent from EVERY file under the package
    chk("R14_marker_absent", not _marker_present(pkg_dir))

    # ---- functionality preserved (credited only alongside a real structural removal, so
    #      a do-nothing submission -- where functionality trivially still holds -- earns
    #      nothing here) ----
    removed_ok = _injected_absent(sp)
    chk("R16_functionality", removed_ok and _functionality_ok(sp))

    return results


def _no_malicious_pth(sp):
    """True iff no .pth in site-packages still executes the injected loader import."""
    try:
        for fn in os.listdir(sp):
            if not fn.endswith(".pth"):
                continue
            try:
                txt = open(os.path.join(sp, fn), "r", errors="replace").read()
            except Exception:
                continue
            for line in txt.splitlines():
                s = line.strip()
                if s.startswith(("import ", "import\t")) and "_autoload" in s:
                    return False
        return True
    except Exception:
        return False


def _injected_absent(sp):
    """True iff the injected artifacts are physically gone, independent of RECORD."""
    pkg = os.path.join(sp, "metricslib")
    if os.path.exists(os.path.join(pkg, "_autoload.py")):
        return False
    if os.path.isdir(os.path.join(pkg, "_resources")):
        return False
    return _no_malicious_pth(sp)


def _marker_present(pkg_dir):
    for dp, _, files in os.walk(pkg_dir):
        if "__pycache__" in dp:
            continue
        for fn in files:
            try:
                data = open(os.path.join(dp, fn), "rb").read()
            except Exception:
                continue
            if INJECTED_MARKER.encode() in data:
                return True
    return False


def _b64_record(digest):
    return "sha256=" + base64.urlsafe_b64encode(digest).decode().rstrip("=")


def _manifest_clean(sp):
    dist = os.path.join(sp, "metricslib-1.4.2.dist-info", "RECORD")
    pkg_dir = os.path.join(sp, "metricslib")
    try:
        listed = {}
        for line in open(dist):
            parts = line.strip().split(",")
            if parts and parts[0].startswith("metricslib/") and len(parts) >= 2 and parts[1]:
                listed[parts[0]] = parts[1].split("=", 1)[1]
        # every listed file present and matching
        for rel, b64 in listed.items():
            fp = os.path.join(sp, rel)
            if not os.path.exists(fp):
                return False
            if _b64_record(hashlib.sha256(open(fp, "rb").read()).digest()).split("=", 1)[1] != b64:
                return False
        # no extra files under the package beyond those listed (ignoring bytecode caches)
        for dp, _, files in os.walk(pkg_dir):
            if "__pycache__" in dp:
                continue
            for fn in files:
                rel = os.path.relpath(os.path.join(dp, fn), sp).replace(os.sep, "/")
                if rel not in listed:
                    return False
        return True
    except Exception:
        return False


def _functionality_ok(sp):
    env = dict(os.environ, PYTHONPATH=sp)
    try:
        out = subprocess.run(
            [sys.executable, "-c",
             "import metricslib;"
             "print(round(metricslib.mean([2,4,6]),6), round(metricslib.pstdev([2,4,6]),6))"],
            env=env, capture_output=True, text=True, timeout=30)
        return out.returncode == 0 and out.stdout.strip() == "4.0 1.632993"
    except Exception:
        return False


# ----------------------------------------------------- weighting + pytest entry points
# Reward = WEIGHTED fraction of independent checks. Items that require genuine payload
# analysis (recovering the env-keyed, XOR-encrypted C2 indicators by static reverse
# engineering -- a naive launch/detonate leaks nothing, and the decoded key/classification
# depend on that recovery) carry weight 3; routine incident-response items (localise,
# identify, and the structural remediation checks) carry weight 1. So a competent agent
# that does everything EXCEPT the payload analysis caps at 9/27 = 0.333, well under the
# difficulty gate, and only genuine reverse engineering reaches 1.0. Analysis items are
# expanded into 3 test instances each so the pytest pass-fraction equals the weighted
# reward under any harness.
CHECKS = [
    ("R01_pth_file", 1), ("R02_loader_module", 1),
    ("R03_c2_host", 3), ("R04_c2_port", 3), ("R05_exfil_endpoint", 3), ("R06_decode_key", 3),
    ("R07_package", 1), ("R08_trigger", 1), ("R09_cwe", 3), ("R10_owasp", 3),
    ("R11_pth_removed", 1), ("R12_autoload_removed", 1), ("R13_manifest_clean", 1),
    ("R14_marker_absent", 1), ("R16_functionality", 1),
]
ANALYSIS_ITEMS = {n for n, w in CHECKS if w == 3}


def weighted_reward(results):
    d = dict(results)
    tot = sum(w for _, w in CHECKS)
    got = sum(w for n, w in CHECKS if d.get(n))
    return got / tot if tot else 0.0


_CACHE = {"results": None}


def _results():
    if _CACHE["results"] is None:
        _CACHE["results"] = dict(run_checks())
    return _CACHE["results"]


try:
    import pytest

    _EXPANDED = [n for n, w in CHECKS for _ in range(w)]

    @pytest.mark.parametrize("check", _EXPANDED)
    def test_weighted_item(check):
        assert _results()[check], check
except ImportError:
    pass
