"""Verifier for mirror-tamper-forensics.  Reward = WEIGHTED fraction of independent checks.

Anti-reward-hacking design:

  * c2_host / c2_port / exfil_endpoint are reachable only through the four-stage static
    decode (base85 -> XOR(key) -> zlib -> marshal) of the staged payload. The host is NOT
    a plaintext constant even after decoding: it is XOR-ENCRYPTED, and the payload derives
    its decryption key at RUNTIME from an environment variable ($GC_BUILD_SIG) that is
    UNSET in the sandbox (environmental keying). So running the payload -- even a "detonate
    and capture the socket call" attempt with the environment generically neutralised --
    decrypts to garbage and never reveals the real host (verified: 0 real-host captures).
    The true key is the module's recorded build signature (the RECORD manifest's clean
    hash); recovering the host requires decoding the payload, understanding the keying,
    recomputing that hash, and decrypting statically -- genuine reverse engineering.
  * actual_hash is matched EXACTLY against the delivered (tampered) file's digest
    (embedded constant), not a wildcard -- a guessed hash fails.
  * Identification/classification fields (package, trigger, CWE, OWASP) are credited
    ONLY when localisation (and, for CWE/OWASP, the decoded host) is already correct,
    so guessing them standalone earns nothing.
  * Remediation is checked STRUCTURALLY (the env-keyed payload emits no beacon in the
    sandbox, so a
    behavioural socket probe would be meaningless): exact restore to the clean RECORD
    hash, the injected marker absent from every package file, a full manifest match with
    the injected resource directory physically gone (not merely de-listed from the
    agent-editable RECORD), and preserved functionality gated on the real restore.
    Delete / stub / manifest-edit / do-nothing all fail these.
  * WEIGHTING (see CHECKS below): the six payload-analysis / un-guessable items carry
    weight 3 and the nine routine incident-response items weight 1, so an agent that does
    everything EXCEPT the genuine payload reverse-engineering caps at 9/27 = 0.333.

The embedded EXPECTED_* constants are cross-checked against a fresh build by
local_test.py, so any drift from env/gen/build_env.py fails the suite loudly.
"""
import base64
import hashlib
import json
import os
import subprocess
import sys
import sysconfig

# --- ground truth (version-independent; cross-checked against build_env in the suite) ---
EXP_HOST = "telemetry.pkg-sync-cdn.net"
EXP_PORT = 8443
EXP_ENDPOINT = "/v2/collect"
EXP_KEY = "9f1c33a75be24d0186ca4471e2d5b8f0"
EXP_TAMPERED_HASH = "33fbe52ef79fc1d99b53b30ce8dc3457317998fe54328b14f867eafede68d1de"
EXP_PKG = "geocache"
EXP_TRIGGER = "import"
EXP_CWE = "CWE-506"
EXP_OWASP = "A08:2021"

INJECTED_MARKER = "build resource cache (autogenerated; do not edit)"
REPORT_KEYS = {
    "compromised_package", "malicious_path", "trigger", "c2_host", "c2_port",
    "exfil_endpoint", "decode_key", "recorded_hash", "actual_hash",
    "primary_cwe", "owasp_a",
}


def _purelib():
    return sysconfig.get_paths()["purelib"]


def _clean_cache_bytes(mirror):
    p = os.path.join(mirror, "geocache-2.3.1", "geocache", "_cache.py")
    with open(p, "rb") as f:
        return f.read()


def _b64_record(digest):
    return "sha256=" + base64.urlsafe_b64encode(digest).decode().rstrip("=")


def _norm(v):
    return str(v).strip()


def run_checks(report_path="/app/report.json", sp=None, mirror="/opt/mirror"):
    """Return an ordered list of (check_name, passed_bool)."""
    sp = sp or _purelib()
    pkg_dir = os.path.join(sp, "geocache")
    grid_cache = os.path.join(pkg_dir, "_cache.py")
    clean_bytes = _clean_cache_bytes(mirror)
    clean_hex = hashlib.sha256(clean_bytes).hexdigest()
    results = []

    def chk(name, cond):
        results.append((name, bool(cond)))

    # ---- load the report (a missing/broken report simply fails every report item) ----
    try:
        with open(report_path) as f:
            rep = json.load(f)
        assert isinstance(rep, dict)
    except Exception:
        rep = {}
    g = lambda k: _norm(rep.get(k, ""))

    # ---- localisation (earned: requires finding the manifest-mismatched file) ----
    path_ok = os.path.normpath(g("malicious_path")) == os.path.normpath(grid_cache)
    chk("R01_malicious_path", path_ok)

    # ---- integrity evidence (earned; exact, not wildcard) ----
    chk("R02_recorded_hash", g("recorded_hash").lower() == clean_hex)
    chk("R03_actual_hash", g("actual_hash").lower() == EXP_TAMPERED_HASH)

    # ---- decode chain (earned: only reachable by the full 4-stage static decode) ----
    host_ok = g("c2_host").lower() == EXP_HOST
    chk("R04_c2_host", host_ok)
    chk("R05_c2_port", host_ok and g("c2_port") == str(EXP_PORT))
    chk("R06_exfil_endpoint", host_ok and g("exfil_endpoint") == EXP_ENDPOINT)
    # credited only once the file is localised, so the plaintext key in _resources is
    # not earnable by a blind grep for the lone 32-hex string with no forensic work
    chk("R07_decode_key", host_ok and g("decode_key").lower() == EXP_KEY)

    # ---- identification/classification (credited ONLY if the earned work is present) ----
    chk("R08_package", path_ok and g("compromised_package").lower() == EXP_PKG)
    chk("R09_trigger", path_ok and g("trigger").lower() == EXP_TRIGGER)
    chk("R10_cwe", path_ok and host_ok
        and g("primary_cwe").upper().replace(" ", "") == EXP_CWE)
    chk("R11_owasp", path_ok and host_ok
        and g("owasp_a").upper().replace(" ", "") == EXP_OWASP)

    # ---- remediation: exact restore to the clean RECORD hash (false at baseline) ----
    try:
        installed = open(grid_cache, "rb").read()
    except Exception:
        installed = b""
    chk("R12_restore_hash", hashlib.sha256(installed).hexdigest() == clean_hex)

    # ---- remediation: full manifest match + no extra files, AND the injected resource
    #      directory physically gone (not merely re-listed in the agent-editable RECORD) ----
    chk("R13_manifest_clean",
        _manifest_clean(sp) and not os.path.isdir(os.path.join(pkg_dir, "_resources")))

    # ---- remediation: injected marker absent from EVERY file under the package ----
    chk("R14_marker_absent", not _marker_present(pkg_dir))

    # ---- functionality preserved (credited only alongside a real restore, so a
    #      do-nothing submission -- where functionality trivially still holds -- earns
    #      nothing here) ----
    restore_ok = hashlib.sha256(installed).hexdigest() == clean_hex
    chk("R16_functionality", restore_ok and _functionality_ok(sp))

    return results


def _manifest_clean(sp):
    dist = os.path.join(sp, "geocache-2.3.1.dist-info", "RECORD")
    pkg_dir = os.path.join(sp, "geocache")
    try:
        listed = {}
        for line in open(dist):
            parts = line.strip().split(",")
            if parts and parts[0].startswith("geocache/") and len(parts) >= 2 and parts[1]:
                listed[parts[0]] = parts[1].split("=", 1)[1]
        # every listed file present and matching
        for rel, b64 in listed.items():
            fp = os.path.join(sp, rel)
            if not os.path.exists(fp):
                return False
            if _b64_record(hashlib.sha256(open(fp, "rb").read()).digest()).split("=", 1)[1] != b64:
                return False
        # no extra files under the package beyond those listed (ignoring bytecode caches)
        for dp, _, files in os.walk(pkg_dir):
            if "__pycache__" in dp:
                continue
            for fn in files:
                rel = os.path.relpath(os.path.join(dp, fn), sp).replace(os.sep, "/")
                if rel not in listed:
                    return False
        return True
    except Exception:
        return False


def _marker_present(pkg_dir):
    for dp, _, files in os.walk(pkg_dir):
        if "__pycache__" in dp:
            continue
        for fn in files:
            try:
                data = open(os.path.join(dp, fn), "rb").read()
            except Exception:
                continue
            if INJECTED_MARKER.encode() in data:
                return True
    return False



def _functionality_ok(sp):
    env = dict(os.environ, PYTHONPATH=sp)
    try:
        out = subprocess.run(
            [sys.executable, "-c",
             "import geocache; print(geocache.encode(37.42, -122.08, 9))"],
            env=env, capture_output=True, text=True, timeout=30)
        return out.returncode == 0 and len(out.stdout.strip()) == 9
    except Exception:
        return False


# ----------------------------------------------------- weighting + pytest entry points
# Reward = WEIGHTED fraction of independent checks. Items that require genuine payload
# analysis (recovering the env-keyed, XOR-encrypted C2 indicators by static reverse
# engineering -- a naive import/detonate leaks nothing, and the decoded key/classification
# depend on that recovery) carry weight 3; routine incident-response items (localise,
# hash, identify, remediate) carry weight 1. So a competent agent that does everything
# EXCEPT the payload analysis caps at 9/27 = 0.333, well under the difficulty gate, and
# only genuine reverse engineering reaches 1.0. Analysis items are expanded into 3 test
# instances each so the pytest pass-fraction equals the weighted reward under any harness.
CHECKS = [
    ("R01_malicious_path", 1), ("R02_recorded_hash", 1), ("R03_actual_hash", 1),
    ("R04_c2_host", 3), ("R05_c2_port", 3), ("R06_exfil_endpoint", 3), ("R07_decode_key", 3),
    ("R08_package", 1), ("R09_trigger", 1), ("R10_cwe", 3), ("R11_owasp", 3),
    ("R12_restore_hash", 1), ("R13_manifest_clean", 1), ("R14_marker_absent", 1),
    ("R16_functionality", 1),
]
ANALYSIS_ITEMS = {n for n, w in CHECKS if w == 3}


def weighted_reward(results):
    d = dict(results)
    tot = sum(w for _, w in CHECKS)
    got = sum(w for n, w in CHECKS if d.get(n))
    return got / tot if tot else 0.0


_CACHE = {"results": None}


def _results():
    if _CACHE["results"] is None:
        _CACHE["results"] = dict(run_checks())
    return _CACHE["results"]


try:
    import pytest

    _EXPANDED = [n for n, w in CHECKS for _ in range(w)]

    @pytest.mark.parametrize("check", _EXPANDED)
    def test_weighted_item(check):
        assert _results()[check], check
except ImportError:
    pass
