"""Verifier for dependency-confusion-pin.  Reward = WEIGHTED fraction of checks.

Anti-reward-hacking design (every check is either un-guessable earned work or a
STRUCTURAL remediation check that is FALSE on the untouched baseline):

  * indicator_host / indicator_port exist in plaintext NOWHERE on disk -- only inside
    a marshalled code object reached by a four-stage static decode
    (base85 -> XOR(key) -> zlib -> marshal), split across two resource files, and the
    host is additionally XOR-encrypted and assembled only inside a guarded branch that a
    plain import never runs. Neither grep, a single decode, nor dynamic detonation
    (the host is XOR-encrypted under a key read at runtime from an unset env var) yields them; recovery requires
    the full static decode plus reversing the host XOR. indicator_port is credited only
    when the host is correct, so a common-port guess earns nothing.
  * trusted_sha256 is RECOMPUTED from the trusted wheel on disk; it is published
    NOWHERE (the mirror index omits it), so it cannot be grepped or guessed.
  * The two artifact paths are credited ONLY when trusted_sha256 is already correct
    (i.e. the responder actually found and hashed the trusted wheel), so a blind
    which-file-is-which guess earns nothing.
  * Identification/classification fields (package, versions, missing control) are
    credited ONLY when BOTH artifacts are correct (hence only after the recompute);
    CWE/OWASP are credited ONLY when the decoded host is correct. Guessing them
    standalone earns nothing.
  * Remediation is checked STRUCTURALLY (no behavioural beacon probe, because the
    guarded payload does not beacon at baseline -- a socket probe would pass on the
    untouched install and break do-nothing=0): (a) the lockfile re-pinned to the
    trusted version with the RECOMPUTED integrity hash while every unrelated line stays
    byte-identical, (b) the installed package's bytes exactly equal the trusted wheel's
    package contents AND the injected marker is absent from every file, and (c)
    preserved functionality, credited only alongside a real restore. Delete/stub/
    symptom-suppression fixes fail (a), (b) and (c); doing nothing scores 0 on all
    three.

Reward is WEIGHTED: the payload-analysis items (the decoded indicator_host/port, and
the CWE/OWASP items that gate on the decoded host) carry weight 5; every routine
incident-response item (recompute hash, identify artifacts, versions, package, control,
re-pin, restore, functionality) carries weight 1. A competent responder who does
everything EXCEPT the payload analysis caps at 10/30 = 0.333, so only genuine reverse
engineering reaches 1.0. Analysis items are expanded into `weight` pytest instances
each so the pytest pass-fraction equals the weighted reward under any harness.

The embedded EXPECTED_* constants are cross-checked against a fresh build by
local_test.py, so any drift from env/gen/build_env.py fails the suite loudly.
"""
import hashlib
import json
import os
import subprocess
import sys
import sysconfig
import zipfile

# --- ground truth (version-independent; cross-checked against build_env in the suite) ---
EXP_PKG = "corp-auth-utils"
EXP_MAL_VER = "2.9.9"
EXP_TRUST_VER = "2.9.0"
EXP_HOST = "collector.authlib-cdn.net"
EXP_PORT = 8444
EXP_CONTROL = "hash-pinning"
EXP_CWE = "CWE-494"
EXP_OWASP = "A08:2021"
MAL_WHEEL = "corp_auth_utils-2.9.9-py3-none-any.whl"
TRUST_WHEEL = "corp_auth_utils-2.9.0-py3-none-any.whl"
PKG_DIRNAME = "corp_auth_utils"

INJECTED_MARKER = "vendor bootstrap cache (autogenerated; do not edit)"

LOCK_BASELINE = (
    "# Locked dependency set - regenerate only via the internal resolver\n"
    "requests==2.31.0 --hash=sha256:"
    "5c3e1f9a4b8d2e6c0a7f1b3d9e2c4a6b8d0f2e4c6a8b0d2f4e6c8a0b2d4f6e8c\n"
    "corp-auth-utils==2.9.9\n"
    "urllib3==2.0.7 --hash=sha256:"
    "9a1b2c3d4e5f60718293a4b5c6d7e8f901a2b3c4d5e6f7081920a3b4c5d6e7f8\n"
)

REPORT_KEYS = {
    "confused_package", "malicious_version", "trusted_version", "malicious_artifact",
    "trusted_artifact", "trusted_sha256", "missing_control", "indicator_host",
    "indicator_port", "primary_cwe", "owasp_a",
}


def _purelib():
    return sysconfig.get_paths()["purelib"]


def _norm(v):
    return str(v).strip()


def _sha256_file(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _trusted_pkg_hashes(trust_wheel):
    """{relpath: sha256} for the package files inside the trusted wheel."""
    out = {}
    with zipfile.ZipFile(trust_wheel) as zf:
        for name in zf.namelist():
            if name.startswith(PKG_DIRNAME + "/") and not name.endswith("/"):
                out[name] = hashlib.sha256(zf.read(name)).hexdigest()
    return out


def _installed_pkg_hashes(sp):
    base = os.path.join(sp, PKG_DIRNAME)
    out = {}
    for dp, _, files in os.walk(base):
        if "__pycache__" in dp:
            continue
        for fn in files:
            fp = os.path.join(dp, fn)
            rel = os.path.relpath(fp, sp).replace(os.sep, "/")
            try:
                out[rel] = hashlib.sha256(open(fp, "rb").read()).hexdigest()
            except Exception:
                out[rel] = None
    return out


def _marker_present(pkg_dir):
    for dp, _, files in os.walk(pkg_dir):
        if "__pycache__" in dp:
            continue
        for fn in files:
            try:
                data = open(os.path.join(dp, fn), "rb").read()
            except Exception:
                continue
            if INJECTED_MARKER.encode() in data:
                return True
    return False


def _functionality_ok(sp):
    env = dict(os.environ, PYTHONPATH=sp)
    try:
        out = subprocess.run(
            [sys.executable, "-c",
             "import corp_auth_utils; print(corp_auth_utils.sign('k', 'm'))"],
            env=env, capture_output=True, text=True, timeout=30)
        return out.returncode == 0 and len(out.stdout.strip()) == 64
    except Exception:
        return False


def _lock_repinned(lock_path, trusted_sha):
    try:
        cur = open(lock_path).read().splitlines()
    except Exception:
        return False
    expected = []
    for line in LOCK_BASELINE.splitlines():
        if line.startswith("corp-auth-utils=="):
            expected.append("corp-auth-utils==%s --hash=sha256:%s"
                            % (EXP_TRUST_VER, trusted_sha))
        else:
            expected.append(line)
    return cur == expected


def run_checks(report_path="/app/report.json", sp=None,
               cache="/opt/pip-cache", build_dir="/app/build"):
    """Return an ordered list of (check_name, passed_bool)."""
    sp = sp or _purelib()
    pkg_dir = os.path.join(sp, PKG_DIRNAME)
    mal_wheel = os.path.join(cache, MAL_WHEEL)
    trust_wheel = os.path.join(cache, TRUST_WHEEL)
    lock_path = os.path.join(build_dir, "requirements.lock")
    trusted_sha = _sha256_file(trust_wheel)
    results = []

    def chk(name, cond):
        results.append((name, bool(cond)))

    try:
        with open(report_path) as f:
            rep = json.load(f)
        assert isinstance(rep, dict)
    except Exception:
        rep = {}
    g = lambda k: _norm(rep.get(k, ""))

    # ---- earned recompute: trusted wheel sha256 (published nowhere) ----
    sha_ok = g("trusted_sha256").lower() == trusted_sha
    chk("A03_trusted_sha256", sha_ok)

    # ---- earned decode: indicators live only in the marshalled payload ----
    host_ok = g("indicator_host").lower() == EXP_HOST
    chk("A04_indicator_host", host_ok)
    chk("A05_indicator_port", host_ok and g("indicator_port") == str(EXP_PORT))

    # ---- earned identification: artifact paths, credited only once the trusted wheel
    #      was actually found + hashed (sha_ok), so a blind which-is-which guess fails --
    mal_path_ok = os.path.normpath(g("malicious_artifact")) == os.path.normpath(mal_wheel)
    trust_path_ok = os.path.normpath(g("trusted_artifact")) == os.path.normpath(trust_wheel)
    a01 = mal_path_ok and sha_ok
    a02 = trust_path_ok and sha_ok
    chk("A01_malicious_artifact", a01)
    chk("A02_trusted_artifact", a02)
    artifacts_ok = a01 and a02

    # ---- identification/classification, credited only after the earned work ----
    chk("A06_confused_package", artifacts_ok and g("confused_package").lower() == EXP_PKG)
    chk("A07_malicious_version", artifacts_ok and g("malicious_version") == EXP_MAL_VER)
    chk("A08_trusted_version", artifacts_ok and g("trusted_version") == EXP_TRUST_VER)
    chk("A09_missing_control",
        artifacts_ok and g("missing_control").strip().lower() == EXP_CONTROL)
    chk("A10_primary_cwe",
        host_ok and g("primary_cwe").upper().replace(" ", "") == EXP_CWE)
    chk("A11_owasp_a",
        host_ok and g("owasp_a").upper().replace(" ", "") == EXP_OWASP)

    # ---- remediation (a): lock re-pinned to trusted build + recomputed hash, every
    #      unrelated line byte-identical (false at baseline) ----
    chk("A12_lock_repinned", _lock_repinned(lock_path, trusted_sha))

    # ---- remediation (b): STRUCTURAL -- the installed package's bytes exactly equal
    #      the trusted wheel's package contents AND the injected marker is absent from
    #      every file. No behavioural socket probe: the guarded payload does not beacon
    #      at baseline, so a probe would pass on the untouched install and silently
    #      break the do-nothing=0 property. A byte-for-byte content match cannot be
    #      faked by symptom suppression and is FALSE on the untouched (malicious)
    #      install (extra _resources files + tampered _signing.py) ----
    content_match = _installed_pkg_hashes(sp) == _trusted_pkg_hashes(trust_wheel)
    installed_clean = content_match and not _marker_present(pkg_dir)
    chk("A13_installed_clean", installed_clean)

    # ---- functionality preserved, credited only alongside a real restore ----
    chk("A14_functionality", installed_clean and _functionality_ok(sp))

    return results


# ----------------------------------------------------- weighting + pytest entry points
# Reward = WEIGHTED fraction of independent checks. Items that require genuine payload
# analysis (recovering the guarded, XOR-encrypted C2 indicators by static reverse
# engineering -- a naive import/detonate leaks nothing, and the CWE/OWASP classification
# gates on that recovery) carry weight 5; routine incident-response items (recompute the
# trusted hash, identify the artifacts, versions, package, control, re-pin, restore,
# functionality) carry weight 1. So a competent agent that does everything EXCEPT the
# payload analysis caps at 10/30 = 0.333, well under the difficulty gate, and only
# genuine reverse engineering reaches 1.0. Analysis items are expanded into `weight`
# test instances each so the pytest pass-fraction equals the weighted reward under any
# harness.
CHECKS = [
    ("A01_malicious_artifact", 1), ("A02_trusted_artifact", 1), ("A03_trusted_sha256", 1),
    ("A04_indicator_host", 5), ("A05_indicator_port", 5),
    ("A06_confused_package", 1), ("A07_malicious_version", 1), ("A08_trusted_version", 1),
    ("A09_missing_control", 1),
    ("A10_primary_cwe", 5), ("A11_owasp_a", 5),
    ("A12_lock_repinned", 1), ("A13_installed_clean", 1), ("A14_functionality", 1),
]
ANALYSIS_ITEMS = {n for n, w in CHECKS if w == 5}


def weighted_reward(results):
    d = dict(results)
    tot = sum(w for _, w in CHECKS)
    got = sum(w for n, w in CHECKS if d.get(n))
    return got / tot if tot else 0.0


_CACHE = {"results": None}


def _results():
    if _CACHE["results"] is None:
        _CACHE["results"] = dict(run_checks())
    return _CACHE["results"]


try:
    import pytest

    _EXPANDED = [n for n, w in CHECKS for _ in range(w)]

    @pytest.mark.parametrize("check", _EXPANDED)
    def test_weighted_item(check):
        assert _results()[check], check
except ImportError:
    pass
